Algoritmo "semnome"

//Desenvolva uma lógica que leia os valores de A, B e C de uma equação do
//segundo grau e mostre o valor de Delta.

Var
 A, B, C: real
 Delta: real

Inicio

 Escreva ("Digite o valor de a: ")
 Leia (A)
 Escreva ("Digite o valor de b: ")
 Leia (B)
 Escreva ("Digite o valor de c: ")
 Leia (C)
 
 Delta <- B^2 - 4*A*C
 
 Escreva ("Valor de Delta: ", Delta)
 
Fimalgoritmo