Algoritmo "CARTEIRA"

// Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira
// (em R$)
// e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45.


Var
   carteira , total: REAL
   dolar : REAL
   
   
Inicio


    ESCREVAL ("DIGITE O VALOR EM R$: ")
    LEIA (carteira)
    

    total <- carteira / dolar
    
    
    
    ESCREVAL ("VOCE TEM R$",carteira," REAIS")
    ESCREVAL ("VOCE PODE GASTAR US$",total," DOLARES")

Fimalgoritmo